# DDPM config used for DDPM training
ddpm:
  data:
    root: ???
    name: "ffhq"
    image_size: 128
    hflip: True
    n_channels: 3
    norm: True

  model:
    dim : 128
    attn_resolutions: "16,"
    n_residual: 2
    dim_mults: "1,2,2,3,4"
    dropout: 0.0
    n_heads: 1
    beta1: 0.0001
    beta2: 0.02
    n_timesteps: 1000


  training:
    seed: 0
    fp16: False
    use_ema: True
    z_cond: False
    z_dim: 1024
    type: 'form1'
    ema_decay: 0.9999
    batch_size: 16
    epochs: 5000
    log_step: 1
    device: "gpu:0"
    chkpt_interval: 1
    optimizer: "Adam"
    lr: 2e-9
    restore_path: ???
    vae_chkpt_path: ???
    results_dir: ???
    workers: 2
    grad_clip: 1.0
    n_anneal_steps: 5000
    loss: "l2"
    chkpt_prefix: ""
    cfd_rate: 0.0
    dummy_vae_chkpt_path: ???

# VAE config used for VAE training
vae:
  data:
    root: ???
    name: "ffhq"
    image_size: 128
    n_channels: 3
    hflip: True

  training:
    seed: 0
    fp16: False
    batch_size: 16
    epochs: 1000
    log_step: 1
    device: "gpu:0"
    chkpt_interval: 1
    optimizer: "Adam"
    lr: 1e-4
    restore_path: ???
    results_dir: ???
    workers: 2
    chkpt_prefix: ""
    alpha: 1.0
    grad_clip: 1.0
